// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH0S6HjsdR4dMOoeBmbXWhyFYtY7IEypw',
    appId: '1:90240735628:web:6860f86416c026d2931ea9',
    messagingSenderId: '90240735628',
    projectId: 'provamobile-59a2b',
    authDomain: 'provamobile-59a2b.firebaseapp.com',
    storageBucket: 'provamobile-59a2b.firebasestorage.app',
    measurementId: 'G-BCHRHGX2YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaUv832ARvu9_0cjK6JGwpXXBsBOQvygQ',
    appId: '1:90240735628:android:a3e8e92f2a507a3e931ea9',
    messagingSenderId: '90240735628',
    projectId: 'provamobile-59a2b',
    storageBucket: 'provamobile-59a2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3wUHQLfZSyt8EsLbO4kvXmUpDRED9soo',
    appId: '1:90240735628:ios:cd6e6df0ee2a8c38931ea9',
    messagingSenderId: '90240735628',
    projectId: 'provamobile-59a2b',
    storageBucket: 'provamobile-59a2b.firebasestorage.app',
    iosBundleId: 'com.example.p2mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3wUHQLfZSyt8EsLbO4kvXmUpDRED9soo',
    appId: '1:90240735628:ios:cd6e6df0ee2a8c38931ea9',
    messagingSenderId: '90240735628',
    projectId: 'provamobile-59a2b',
    storageBucket: 'provamobile-59a2b.firebasestorage.app',
    iosBundleId: 'com.example.p2mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH0S6HjsdR4dMOoeBmbXWhyFYtY7IEypw',
    appId: '1:90240735628:web:befb69e88c54c70a931ea9',
    messagingSenderId: '90240735628',
    projectId: 'provamobile-59a2b',
    authDomain: 'provamobile-59a2b.firebaseapp.com',
    storageBucket: 'provamobile-59a2b.firebasestorage.app',
    measurementId: 'G-FNPV75XWJB',
  );
}
